// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ5BQQOX8P72XEBJYimiPPcpQ-rihkX1g',
    appId: '1:968358300997:web:bbe6ec9e6548e1c435c22c',
    messagingSenderId: '968358300997',
    projectId: 'atelier4-y-eassi-iir5g2',
    authDomain: 'atelier4-y-eassi-iir5g2.firebaseapp.com',
    storageBucket: 'atelier4-y-eassi-iir5g2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzl5J2_fZVEWd2PGT3OU4q3ugUaADSrQI',
    appId: '1:968358300997:android:11ed2e2f2d049a3535c22c',
    messagingSenderId: '968358300997',
    projectId: 'atelier4-y-eassi-iir5g2',
    storageBucket: 'atelier4-y-eassi-iir5g2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPt67zg8-stoLNtjEznzyYpu8XMMYbnWc',
    appId: '1:968358300997:ios:ffdbf3b842cc75f535c22c',
    messagingSenderId: '968358300997',
    projectId: 'atelier4-y-eassi-iir5g2',
    storageBucket: 'atelier4-y-eassi-iir5g2.appspot.com',
    iosBundleId: 'com.example.atelier4YEsslassiIir5g2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPt67zg8-stoLNtjEznzyYpu8XMMYbnWc',
    appId: '1:968358300997:ios:ffdbf3b842cc75f535c22c',
    messagingSenderId: '968358300997',
    projectId: 'atelier4-y-eassi-iir5g2',
    storageBucket: 'atelier4-y-eassi-iir5g2.appspot.com',
    iosBundleId: 'com.example.atelier4YEsslassiIir5g2',
  );
}
